---
- name: artifactory | Install dependencies
  yum: pkg={{ item }} state=installed
  become: yes
  with_items:
    - unzip
    - net-tools
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
  tags: artifactory

- name: artifactory | Download artifactory zip
  become: yes
  get_url: url={{ artifactory_zip_url }} dest=/opt/{{ artifactory_zip_file }}

- name: artifactory | Extract artifactory
  become: yes
  shell: unzip /opt/{{ artifactory_zip_file }} -d /opt  creates={{ artifactory_dir }}


- name: artifactory | Getting in to installation directory
  become: yes
  shell: cd /opt/artifactory-oss-6.8.4/bin

- name: artifactory| Install service
  become: yes
  shell: bash /opt/artifactory-oss-6.8.4/bin/installService.sh

- name: artifactory | Start/Restart artifactory
  become: yes
  service: name=artifactory state=started
